// Country code to Prisma enum mapping utility
// Maps alpha3 codes (e.g., "IND") to Prisma enum values (e.g., "INDIA")

export const countryCodeToEnum: Record<string, string> = {
  // A
  'ASC': 'ASCENSION_ISLAND',
  'AND': 'ANDORRA',
  'ARE': 'UNITED_ARAB_EMIRATES',
  'AFG': 'AFGHANISTAN',
  'ATG': 'ANTIGUA_AND_BARBUDA',
  'AIA': 'ANGUILLA',
  'ALB': 'ALBANIA',
  'ARM': 'ARMENIA',
  'AGO': 'ANGOLA',
  'ATA': 'ANTARCTICA',
  'ARG': 'ARGENTINA',
  'ASM': 'AMERICAN_SAMOA',
  'AUT': 'AUSTRIA',
  'AUS': 'AUSTRALIA',
  'ABW': 'ARUBA',
  'ALA': 'ALAND_ISLANDS',
  'AZE': 'AZERBAIJAN',
  'BIH': 'BOSNIA_HERZEGOVINA',
  'BRB': 'BARBADOS',
  'BGD': 'BANGLADESH',
  'BEL': 'BELGIUM',
  'BFA': 'BURKINA_FASO',
  'BGR': 'BULGARIA',
  'BHR': 'BAHRAIN',
  'BDI': 'BURUNDI',
  'BEN': 'BENIN',
  'BLM': 'SAINT_BARTHELEMY',
  'BMU': 'BERMUDA',
  'BRN': 'BRUNEI_DARUSSALAM',
  'BOL': 'BOLIVIA',
  'BES': 'BONAIRE_SINT_EUSTATIUS_AND_SABA',
  'BRA': 'BRAZIL',
  'BHS': 'BAHAMAS',
  'BTN': 'BHUTAN',
  'BVT': 'BOUVET_ISLAND',
  'BWA': 'BOTSWANA',
  'BLR': 'BELARUS',
  'BLZ': 'BELIZE',
  
  // C
  'CAN': 'CANADA',
  'CCK': 'COCOS_KEELING_ISLANDS',
  'COD': 'DEMOCRATIC_REPUBLIC_OF_CONGO',
  'CAF': 'CENTRAL_AFRICAN_REPUBLIC',
  'COG': 'REPUBLIC_OF_CONGO',
  'CHE': 'SWITZERLAND',
  'CIV': 'COTE_DIVOIRE',
  'COK': 'COOK_ISLANDS',
  'CHL': 'CHILE',
  'CMR': 'CAMEROON',
  'CHN': 'CHINA',
  'COL': 'COLOMBIA',
  'CRI': 'COSTA_RICA',
  'CUB': 'CUBA',
  'CPV': 'CABO_VERDE',
  'CUW': 'CURACAO',
  'CXR': 'CHRISTMAS_ISLAND',
  'CYP': 'CYPRUS',
  'CZE': 'CZECH_REPUBLIC',
  
  // D
  'DEU': 'GERMANY',
  'DJI': 'DJIBOUTI',
  'DNK': 'DENMARK',
  'DMA': 'DOMINICA',
  'DOM': 'DOMINICAN_REPUBLIC',
  'DZA': 'ALGERIA',
  
  // E
  'ECU': 'ECUADOR',
  'EST': 'ESTONIA',
  'EGY': 'EGYPT',
  'ESH': 'WESTERN_SAHARA',
  'ERI': 'ERITREA',
  'ESP': 'SPAIN',
  'ETH': 'ETHIOPIA',
  
  // F
  'FIN': 'FINLAND',
  'FJI': 'FIJI',
  'FLK': 'FALKLAND_ISLANDS',
  'FSM': 'MICRONESIA',
  'FRO': 'FAROE_ISLANDS',
  'FRA': 'FRANCE',
  'GAB': 'GABON',
  'GBR': 'UNITED_KINGDOM',
  'GRD': 'GRENADA',
  'GEO': 'GEORGIA',
  'GUF': 'FRENCH_GUIANA',
  'GGY': 'GUERNSEY',
  'GHA': 'GHANA',
  'GIB': 'GIBRALTAR',
  'GRL': 'GREENLAND',
  'GMB': 'GAMBIA',
  'GIN': 'GUINEA',
  'GLP': 'GUADELOUPE',
  'GNQ': 'EQUATORIAL_GUINEA',
  'GRC': 'GREECE',
  'SGS': 'SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS',
  'GTM': 'GUATEMALA',
  'GUM': 'GUAM',
  'GNB': 'GUINEA_BISSAU',
  'GUY': 'GUYANA',
  
  // H
  'HKG': 'HONG_KONG',
  'HMD': 'HEARD_ISLAND_AND_MCDONALD_ISLANDS',
  'HND': 'HONDURAS',
  'HRV': 'CROATIA',
  'HTI': 'HAITI',
  'HUN': 'HUNGARY',
  
  // I
  'IDN': 'INDONESIA',
  'IRL': 'IRELAND',
  'ISR': 'ISRAEL',
  'IMN': 'ISLE_OF_MAN',
  'IND': 'INDIA',
  'IOT': 'BRITISH_INDIAN_OCEAN_TERRITORY',
  'IRQ': 'IRAQ',
  'IRN': 'IRAN',
  'ISL': 'ICELAND',
  'ITA': 'ITALY',
  
  // J
  'JEY': 'JERSEY',
  'JAM': 'JAMAICA',
  'JOR': 'JORDAN',
  'JPN': 'JAPAN',
  
  // K
  'KEN': 'KENYA',
  'KGZ': 'KYRGYZSTAN',
  'KHM': 'CAMBODIA',
  'KIR': 'KIRIBATI',
  'COM': 'COMOROS',
  'KNA': 'SAINT_KITTS_AND_NEVIS',
  'PRK': 'NORTH_KOREA',
  'KOR': 'SOUTH_KOREA',
  'KWT': 'KUWAIT',
  'CYM': 'CAYMAN_ISLANDS',
  'KAZ': 'KAZAKHSTAN',
  'LAO': 'LAOS',
  'LBN': 'LEBANON',
  'LCA': 'SAINT_LUCIA',
  'LIE': 'LIECHTENSTEIN',
  'LKA': 'SRI_LANKA',
  'LBR': 'LIBERIA',
  'LSO': 'LESOTHO',
  'LTU': 'LITHUANIA',
  'LUX': 'LUXEMBOURG',
  'LVA': 'LATVIA',
  'LBY': 'LIBYA',
  
  // M
  'MAR': 'MOROCCO',
  'MCO': 'MONACO',
  'MDA': 'MOLDOVA',
  'MNE': 'MONTENEGRO',
  'MAF': 'SAINT_MARTIN',
  'MDG': 'MADAGASCAR',
  'MHL': 'MARSHALL_ISLANDS',
  'MKD': 'NORTH_MACEDONIA',
  'MLI': 'MALI',
  'MMR': 'MYANMAR',
  'MNG': 'MONGOLIA',
  'MAC': 'MACAO',
  'MNP': 'NORTHERN_MARIANA_ISLANDS',
  'MTQ': 'MARTINIQUE',
  'MRT': 'MAURITANIA',
  'MSR': 'MONTSERRAT',
  'MLT': 'MALTA',
  'MUS': 'MAURITIUS',
  'MDV': 'MALDIVES',
  'MWI': 'MALAWI',
  'MEX': 'MEXICO',
  'MYS': 'MALAYSIA',
  'MOZ': 'MOZAMBIQUE',
  'NAM': 'NAMIBIA',
  'NCL': 'NEW_CALEDONIA',
  'NER': 'NIGER',
  'NFK': 'NORFOLK_ISLAND',
  'NGA': 'NIGERIA',
  'NIC': 'NICARAGUA',
  'NLD': 'NETHERLANDS',
  'NOR': 'NORWAY',
  'NPL': 'NEPAL',
  'NRU': 'NAURU',
  'NIU': 'NIUE',
  'NZL': 'NEW_ZEALAND',
  
  // O
  'OMN': 'OMAN',
  
  // P
  'PAN': 'PANAMA',
  'PER': 'PERU',
  'PYF': 'FRENCH_POLYNESIA',
  'PNG': 'PAPUA_NEW_GUINEA',
  'PHL': 'PHILIPPINES',
  'PAK': 'PAKISTAN',
  'POL': 'POLAND',
  'SPM': 'SAINT_PIERRE_AND_MIQUELON',
  'PCN': 'PITCAIRN',
  'PRI': 'PUERTO_RICO',
  'PSE': 'PALESTINE',
  'PRT': 'PORTUGAL',
  'PLW': 'PALAU',
  'PRY': 'PARAGUAY',
  
  // Q
  'QAT': 'QATAR',
  'REU': 'REUNION',
  'ROU': 'ROMANIA',
  'SRB': 'SERBIA',
  'RUS': 'RUSSIA',
  'RWA': 'RWANDA',
  'SAU': 'SAUDI_ARABIA',
  'SLB': 'SOLOMON_ISLANDS',
  'SYC': 'SEYCHELLES',
  'SDN': 'SUDAN',
  'SWE': 'SWEDEN',
  'SGP': 'SINGAPORE',
  'SHN': 'SAINT_HELENA',
  'SVN': 'SLOVENIA',
  'SJM': 'SVALBARD_AND_JAN_MAYEN',
  'SVK': 'SLOVAKIA',
  'SLE': 'SIERRA_LEONE',
  'SMR': 'SAN_MARINO',
  'SEN': 'SENEGAL',
  'SOM': 'SOMALIA',
  'SUR': 'SURINAME',
  'SSD': 'SOUTH_SUDAN',
  'STP': 'SAO_TOME_AND_PRINCIPE',
  'SLV': 'EL_SALVADOR',
  'SXM': 'SINT_MAARTEN',
  'SYR': 'SYRIA',
  'SWZ': 'ESWATINI',
  'TCA': 'TURKS_AND_CAICOS_ISLANDS',
  'TCD': 'CHAD',
  'ATF': 'FRENCH_SOUTHERN_TERRITORIES',
  'TGO': 'TOGO',
  'THA': 'THAILAND',
  'TJK': 'TAJIKISTAN',
  'TKL': 'TOKELAU',
  'TLS': 'TIMOR_LESTE',
  'TKM': 'TURKMENISTAN',
  'TUN': 'TUNISIA',
  'TON': 'TONGA',
  'TUR': 'TURKEY',
  'TTO': 'TRINIDAD_AND_TOBAGO',
  'TUV': 'TUVALU',
  'TWN': 'TAIWAN',
  'TZA': 'TANZANIA',
  'UKR': 'UKRAINE',
  'UGA': 'UGANDA',
  'UMI': 'UNITED_STATES_MINOR_OUTLYING_ISLANDS',
  'USA': 'UNITED_STATES',
  'URY': 'URUGUAY',
  'UZB': 'UZBEKISTAN',
  'VAT': 'VATICAN_CITY',
  'VCT': 'SAINT_VINCENT_AND_THE_GRENADINES',
  'VEN': 'VENEZUELA',
  'VGB': 'BRITISH_VIRGIN_ISLANDS',
  'VIR': 'US_VIRGIN_ISLANDS',
  'VNM': 'VIETNAM',
  'VUT': 'VANUATU',
  'WLF': 'WALLIS_AND_FUTUNA',
  'WSM': 'SAMOA',
  'XKX': 'KOSOVO',
  'YEM': 'YEMEN',
  'MYT': 'MAYOTTE',
  'ZAF': 'SOUTH_AFRICA',
  'ZMB': 'ZAMBIA',
  'ZWE': 'ZIMBABWE'
};

// Reverse mapping for validation
export const countryEnumToCode: Record<string, string> = Object.entries(countryCodeToEnum).reduce(
  (acc, [code, enumValue]) => {
    acc[enumValue] = code;
    return acc;
  },
  {} as Record<string, string>
);

// Helper function to convert alpha3 to enum
export function alpha3ToCountryEnum(alpha3: string): string | null {
  return countryCodeToEnum[alpha3.toUpperCase()] || null;
}

// Helper function to convert enum to alpha3
export function countryEnumToAlpha3(enumValue: string): string | null {
  return countryEnumToCode[enumValue] || null;
}

// Validate if alpha3 code is supported
export function isValidAlpha3Code(alpha3: string): boolean {
  return alpha3.toUpperCase() in countryCodeToEnum;
}
